package ni.com.casapellas.cxccobro.cxc;

// Generated Dec 29, 2011 4:46:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * Antiguedad generated by hbm2java
 */
public class Antiguedad implements java.io.Serializable {

	private long idas;
	private Hdrestcta hdrestcta;
	private int inicio;
	private int fin;
	private BigDecimal saldo;
	private String moneda;

	public Antiguedad() {
	}

	public Antiguedad(long idas, Hdrestcta hdrestcta, int inicio, int fin,
			BigDecimal saldo, String moneda) {
		this.idas = idas;
		this.hdrestcta = hdrestcta;
		this.inicio = inicio;
		this.fin = fin;
		this.saldo = saldo;
		this.moneda = moneda;
	}

	public long getIdas() {
		return this.idas;
	}

	public void setIdas(long idas) {
		this.idas = idas;
	}

	public Hdrestcta getHdrestcta() {
		return this.hdrestcta;
	}

	public void setHdrestcta(Hdrestcta hdrestcta) {
		this.hdrestcta = hdrestcta;
	}

	public int getInicio() {
		return this.inicio;
	}

	public void setInicio(int inicio) {
		this.inicio = inicio;
	}

	public int getFin() {
		return this.fin;
	}

	public void setFin(int fin) {
		this.fin = fin;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

}
