package ni.com.casapellas.cxccobro.cxc;

// Generated Dec 29, 2011 4:46:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Detestcta generated by hbm2java
 */
public class Detestcta implements java.io.Serializable {

	private long iddec;
	private long idec;
	private Hdrestcta hdrestcta;
	private String codsuc;
	private String codunineg;
	private int nodoc;
	private String tipodoc;
	private String partida;
	private int nodocm;
	private String tipodocm;
	private Date fecha;
	private Date fechavcto;
	private BigDecimal monto;
	private BigDecimal montop;
	private String moneda;
	private String concepto;
	private int tipomov;
	private int nodoco;
	private String tipodoco;
	private Date fechafact;
	/*********************/
	private BigDecimal montocuota;
	private BigDecimal principal;
	private BigDecimal interesc;
	private BigDecimal iva;
	private BigDecimal interesm;
	private Date fechapago;
	private Date fechaabono;
	private int norecibo;
	private BigDecimal montoapagar;
	private BigDecimal montopago;
	private BigDecimal saldo;
	private String cuota;	
	private BigDecimal saldoLiquidacion;
	private BigDecimal saldoPrincipal;
	private BigDecimal seguro;
	private BigDecimal otroscargos;
	/********************/
	public Detestcta() {
	}

	public Detestcta(long iddec, Hdrestcta hdrestcta, String codsuc,
			String codunineg, int nodoc, String tipodoc, String partida,
			int nodocm, String tipodocm, Date fecha, Date fechavcto,
			BigDecimal monto, BigDecimal montop, String moneda,
			String concepto, int tipomov, int nodoco, String tipodoco, Date fechafact) {
		this.iddec = iddec;
		this.hdrestcta = hdrestcta;
		this.codsuc = codsuc;
		this.codunineg = codunineg;
		this.nodoc = nodoc;
		this.tipodoc = tipodoc;
		this.partida = partida;
		this.nodocm = nodocm;
		this.tipodocm = tipodocm;
		this.fecha = fecha;
		this.fechavcto = fechavcto;
		this.monto = monto;
		this.montop = montop;
		this.moneda = moneda;
		this.concepto = concepto;
		this.tipomov = tipomov;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.fechafact = fechafact;
	}

	public long getIddec() {
		return this.iddec;
	}

	public void setIddec(long iddec) {
		this.iddec = iddec;
	}

	public Hdrestcta getHdrestcta() {
		return this.hdrestcta;
	}

	public void setHdrestcta(Hdrestcta hdrestcta) {
		this.hdrestcta = hdrestcta;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public int getNodoc() {
		return this.nodoc;
	}

	public void setNodoc(int nodoc) {
		this.nodoc = nodoc;
	}

	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public String getPartida() {
		return this.partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	public int getNodocm() {
		return this.nodocm;
	}

	public void setNodocm(int nodocm) {
		this.nodocm = nodocm;
	}

	public String getTipodocm() {
		return this.tipodocm;
	}

	public void setTipodocm(String tipodocm) {
		this.tipodocm = tipodocm;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechavcto() {
		return this.fechavcto;
	}

	public void setFechavcto(Date fechavcto) {
		this.fechavcto = fechavcto;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getMontop() {
		return this.montop;
	}

	public void setMontop(BigDecimal montop) {
		this.montop = montop;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public int getTipomov() {
		return this.tipomov;
	}

	public void setTipomov(int tipomov) {
		this.tipomov = tipomov;
	}

	public int getNodoco() {
		return this.nodoco;
	}

	public void setNodoco(int nodoco) {
		this.nodoco = nodoco;
	}

	public String getTipodoco() {
		return this.tipodoco;
	}

	public void setTipodoco(String tipodoco) {
		this.tipodoco = tipodoco;
	}

	public BigDecimal getMontocuota() {
		return montocuota;
	}

	public void setMontocuota(BigDecimal montocuota) {
		this.montocuota = montocuota;
	}

	public BigDecimal getPrincipal() {
		return principal;
	}

	public void setPrincipal(BigDecimal principal) {
		this.principal = principal;
	}

	public BigDecimal getInteresc() {
		return interesc;
	}

	public void setInteresc(BigDecimal interesc) {
		this.interesc = interesc;
	}

	public BigDecimal getIva() {
		return iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	public BigDecimal getInteresm() {
		return interesm;
	}

	public void setInteresm(BigDecimal interesm) {
		this.interesm = interesm;
	}

	public Date getFechapago() {
		return fechapago;
	}

	public void setFechapago(Date fechapago) {
		this.fechapago = fechapago;
	}

	public int getNorecibo() {
		return norecibo;
	}

	public void setNorecibo(int norecibo) {
		this.norecibo = norecibo;
	}

	
	public BigDecimal getMontopago() {
		return montopago;
	}

	public void setMontopago(BigDecimal montopago) {
		this.montopago = montopago;
	}

	public BigDecimal getSaldo() {
		return saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getCuota() {
		return cuota;
	}

	public void setCuota(String cuota) {
		this.cuota = cuota;
	}

	public Date getFechaabono() {
		return fechaabono;
	}

	public void setFechaabono(Date fechaabono) {
		this.fechaabono = fechaabono;
	}

	public BigDecimal getSaldoLiquidacion() {
		return saldoLiquidacion;
	}

	public void setSaldoLiquidacion(BigDecimal saldoLiquidacion) {
		this.saldoLiquidacion = saldoLiquidacion;
	}
	public Date getFechafact() {
		return this.fechafact;
	}

	public void setFechafact(Date fechafact) {
		this.fechafact = fechafact;
	}

	public BigDecimal getSaldoPrincipal() {
		return saldoPrincipal;
	}

	public void setSaldoPrincipal(BigDecimal saldoPrincipal) {
		this.saldoPrincipal = saldoPrincipal;
	}

	public BigDecimal getMontoapagar() {
		return montoapagar;
	}

	public void setMontoapagar(BigDecimal montoapagar) {
		this.montoapagar = montoapagar;
	}

	public BigDecimal getSeguro() {
		return seguro;
	}

	public void setSeguro(BigDecimal seguro) {
		this.seguro = seguro;
	}

	public BigDecimal getOtroscargos() {
		return otroscargos;
	}

	public void setOtroscargos(BigDecimal otroscargos) {
		this.otroscargos = otroscargos;
	}

	public long getIdec() {
		return idec;
	}

	public void setIdec(long idec) {
		this.idec = idec;
	}
	
}
