package ni.com.casapellas.cxccobro.cxc;

// Generated Jan 3, 2012 2:41:55 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Logestcta generated by hbm2java
 */
public class Logestcta implements java.io.Serializable {

	private int idlogestcta;
	private Date fechacrea;
	private Date fechamod;
	private Date horainicio;
	private Date horafinaliza;
	private int usrmod;
	private long cantdetcarg;
	private int estadocd;
	private String programa;
	private String observacion;
	private String filtros;
	private int mes;
	private int anio;
	private Set hdrestctas = new HashSet(0);

	public Logestcta() {
	}

	public Logestcta(int idlogestcta, Date fechacrea, Date fechamod,
			Date horainicio, Date horafinaliza, int usrmod, long cantdetcarg,
			int estadocd, String programa, String observacion, String filtros,
			int mes, int anio) {
		this.idlogestcta = idlogestcta;
		this.fechacrea = fechacrea;
		this.fechamod = fechamod;
		this.horainicio = horainicio;
		this.horafinaliza = horafinaliza;
		this.usrmod = usrmod;
		this.cantdetcarg = cantdetcarg;
		this.estadocd = estadocd;
		this.programa = programa;
		this.observacion = observacion;
		this.filtros = filtros;
		this.mes = mes;
		this.anio = anio;
	}

	public Logestcta(int idlogestcta, Date fechacrea, Date fechamod,
			Date horainicio, Date horafinaliza, int usrmod, long cantdetcarg,
			int estadocd, String programa, String observacion, String filtros,
			int mes, int anio, Set hdrestctas) {
		this.idlogestcta = idlogestcta;
		this.fechacrea = fechacrea;
		this.fechamod = fechamod;
		this.horainicio = horainicio;
		this.horafinaliza = horafinaliza;
		this.usrmod = usrmod;
		this.cantdetcarg = cantdetcarg;
		this.estadocd = estadocd;
		this.programa = programa;
		this.observacion = observacion;
		this.filtros = filtros;
		this.mes = mes;
		this.anio = anio;
		this.hdrestctas = hdrestctas;
	}

	public int getIdlogestcta() {
		return this.idlogestcta;
	}

	public void setIdlogestcta(int idlogestcta) {
		this.idlogestcta = idlogestcta;
	}

	public Date getFechacrea() {
		return this.fechacrea;
	}

	public void setFechacrea(Date fechacrea) {
		this.fechacrea = fechacrea;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Date getHorainicio() {
		return this.horainicio;
	}

	public void setHorainicio(Date horainicio) {
		this.horainicio = horainicio;
	}

	public Date getHorafinaliza() {
		return this.horafinaliza;
	}

	public void setHorafinaliza(Date horafinaliza) {
		this.horafinaliza = horafinaliza;
	}

	public int getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(int usrmod) {
		this.usrmod = usrmod;
	}

	public long getCantdetcarg() {
		return this.cantdetcarg;
	}

	public void setCantdetcarg(long cantdetcarg) {
		this.cantdetcarg = cantdetcarg;
	}

	public int getEstadocd() {
		return this.estadocd;
	}

	public void setEstadocd(int estadocd) {
		this.estadocd = estadocd;
	}

	public String getPrograma() {
		return this.programa;
	}

	public void setPrograma(String programa) {
		this.programa = programa;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getFiltros() {
		return this.filtros;
	}

	public void setFiltros(String filtros) {
		this.filtros = filtros;
	}

	public int getMes() {
		return this.mes;
	}

	public void setMes(int mes) {
		this.mes = mes;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public Set getHdrestctas() {
		return this.hdrestctas;
	}

	public void setHdrestctas(Set hdrestctas) {
		this.hdrestctas = hdrestctas;
	}

}
