package ni.com.casapellas.cxccobro.cxc;

// default package
// Generated 01-23-2012 04:29:07 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ResumenFinan generated by hbm2java
 */
public class ResumenFinan implements java.io.Serializable {

	private int idrf;
	private Hdrestcta hdrestcta;
	private int nofactura;
	private String producto;
	private String codsuc;
	private Date fechaini;
	private BigDecimal montorig;
	private Date fechasig;
	private int nocuota;
	private BigDecimal montocuota;
	private BigDecimal principal;
	private BigDecimal interesc;
	private BigDecimal interesm;
	private BigDecimal otros;
	private BigDecimal saldopri;
	
	private int nosol;
	private String nomsuc;
	private BigDecimal totalcuota;
	private Date fechapago;
	private BigDecimal mora;
	public ResumenFinan() {
	}

	public ResumenFinan(int idrf, Hdrestcta hdrestcta, int nofactura,
			String producto, String codsuc, Date fechaini, BigDecimal montorig,
			Date fechasig, int nocuota, BigDecimal montocuota,
			BigDecimal principal, BigDecimal interesc, BigDecimal interesm,
			BigDecimal otros, BigDecimal saldopri, int nosol) {
		this.idrf = idrf;
		this.hdrestcta = hdrestcta;
		this.nofactura = nofactura;
		this.producto = producto;
		this.codsuc = codsuc;
		this.fechaini = fechaini;
		this.montorig = montorig;
		this.fechasig = fechasig;
		this.nocuota = nocuota;
		this.montocuota = montocuota;
		this.principal = principal;
		this.interesc = interesc;
		this.interesm = interesm;
		this.otros = otros;
		this.saldopri = saldopri;
		this.nosol = nosol;
	}

	public int getIdrf() {
		return this.idrf;
	}

	public void setIdrf(int idrf) {
		this.idrf = idrf;
	}

	public Hdrestcta getHdrestcta() {
		return this.hdrestcta;
	}

	public void setHdrestcta(Hdrestcta hdrestcta) {
		this.hdrestcta = hdrestcta;
	}

	public int getNofactura() {
		return this.nofactura;
	}

	public void setNofactura(int nofactura) {
		this.nofactura = nofactura;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public Date getFechaini() {
		return this.fechaini;
	}

	public void setFechaini(Date fechaini) {
		this.fechaini = fechaini;
	}

	public BigDecimal getMontorig() {
		return this.montorig;
	}

	public void setMontorig(BigDecimal montorig) {
		this.montorig = montorig;
	}

	public Date getFechasig() {
		return this.fechasig;
	}

	public void setFechasig(Date fechasig) {
		this.fechasig = fechasig;
	}

	public int getNocuota() {
		return this.nocuota;
	}

	public void setNocuota(int nocuota) {
		this.nocuota = nocuota;
	}

	public BigDecimal getMontocuota() {
		return this.montocuota;
	}

	public void setMontocuota(BigDecimal montocuota) {
		this.montocuota = montocuota;
	}

	public BigDecimal getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(BigDecimal principal) {
		this.principal = principal;
	}

	public BigDecimal getInteresc() {
		return this.interesc;
	}

	public void setInteresc(BigDecimal interesc) {
		this.interesc = interesc;
	}

	public BigDecimal getInteresm() {
		return this.interesm;
	}

	public void setInteresm(BigDecimal interesm) {
		this.interesm = interesm;
	}

	public BigDecimal getOtros() {
		return this.otros;
	}

	public void setOtros(BigDecimal otros) {
		this.otros = otros;
	}

	public BigDecimal getSaldopri() {
		return this.saldopri;
	}

	public void setSaldopri(BigDecimal saldopri) {
		this.saldopri = saldopri;
	}

	public int getNosol() {
		return nosol;
	}

	public void setNosol(int nosol) {
		this.nosol = nosol;
	}

	public String getNomsuc() {
		return nomsuc;
	}

	public void setNomsuc(String nomsuc) {
		this.nomsuc = nomsuc;
	}

	public BigDecimal getTotalcuota() {
		return totalcuota;
	}

	public void setTotalcuota(BigDecimal totalcuota) {
		this.totalcuota = totalcuota;
	}

	public Date getFechapago() {
		return fechapago;
	}

	public void setFechapago(Date fechapago) {
		this.fechapago = fechapago;
	}

	public BigDecimal getMora() {
		return mora;
	}

	public void setMora(BigDecimal mora) {
		this.mora = mora;
	}
	
}
