package ni.com.casapellas.cxccobro.cxc;

// Generated Jan 14, 2012 1:23:29 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwdetestadoctaId generated by hbm2java
 */
public class VwdetestadoctaId implements java.io.Serializable {

	private long idec;
	private String codcomp;
	private int codclie;
	private int mes;
	private int anio;
	private BigDecimal saldoantd;
	private BigDecimal saldod;
	private BigDecimal principald;
	private BigDecimal ineteresmd;
	private BigDecimal cargoadmind;
	private BigDecimal saldoantf;
	private BigDecimal principalf;
	private BigDecimal interesmf;
	private BigDecimal cargoadminf;
	private int nosol;
	private String tiposol;
	private String hechopor;
	private Date fechaec;
	private BigDecimal saldof;
	private long iddec;
	private String codsuc;
	private String codunineg;
	private int nodoc;
	private String tipodoc;
	private String partida;
	private int nodocm;
	private String tipodocm;
	private Date fecha;
	private Date fechavcto;
	private BigDecimal monto;
	private BigDecimal montop;
	private String moneda;
	private String concepto;
	private int tipomov;
	private int nodoco;
	private String tipodoco;
	private String nombre;
	private String domicilio;
	private String correoe;
	private String unegocio;
	private String tipomovimiento;
	private String estadoec;
	private int codestadoec;
	private int idlogestcta;
	private String drdl01;
	private Date fechafact;

	public VwdetestadoctaId() {
	}

	public VwdetestadoctaId(long idec, String codcomp, int codclie, int mes,
			int anio, BigDecimal saldoantd, BigDecimal saldod,
			BigDecimal principald, BigDecimal ineteresmd,
			BigDecimal cargoadmind, BigDecimal saldoantf,
			BigDecimal principalf, BigDecimal interesmf,
			BigDecimal cargoadminf, int nosol, String tiposol, String hechopor,
			Date fechaec, BigDecimal saldof, long iddec, String codsuc,
			String codunineg, int nodoc, String tipodoc, String partida,
			int nodocm, String tipodocm, Date fecha, Date fechavcto,
			BigDecimal monto, BigDecimal montop, String moneda,
			String concepto, int tipomov, int nodoco, String tipodoco,
			String nombre, String domicilio, String correoe, String unegocio,
			String tipomovimiento, int codestadoec, int idlogestcta,
			String drdl01, Date fechafact) {
		this.idec = idec;
		this.codcomp = codcomp;
		this.codclie = codclie;
		this.mes = mes;
		this.anio = anio;
		this.saldoantd = saldoantd;
		this.saldod = saldod;
		this.principald = principald;
		this.ineteresmd = ineteresmd;
		this.cargoadmind = cargoadmind;
		this.saldoantf = saldoantf;
		this.principalf = principalf;
		this.interesmf = interesmf;
		this.cargoadminf = cargoadminf;
		this.nosol = nosol;
		this.tiposol = tiposol;
		this.hechopor = hechopor;
		this.fechaec = fechaec;
		this.saldof = saldof;
		this.iddec = iddec;
		this.codsuc = codsuc;
		this.codunineg = codunineg;
		this.nodoc = nodoc;
		this.tipodoc = tipodoc;
		this.partida = partida;
		this.nodocm = nodocm;
		this.tipodocm = tipodocm;
		this.fecha = fecha;
		this.fechavcto = fechavcto;
		this.monto = monto;
		this.montop = montop;
		this.moneda = moneda;
		this.concepto = concepto;
		this.tipomov = tipomov;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.nombre = nombre;
		this.domicilio = domicilio;
		this.correoe = correoe;
		this.unegocio = unegocio;
		this.tipomovimiento = tipomovimiento;
		this.codestadoec = codestadoec;
		this.idlogestcta = idlogestcta;
		this.drdl01 = drdl01;
		this.fechafact = fechafact;
	}

	public VwdetestadoctaId(long idec, String codcomp, int codclie, int mes,
			int anio, BigDecimal saldoantd, BigDecimal saldod,
			BigDecimal principald, BigDecimal ineteresmd,
			BigDecimal cargoadmind, BigDecimal saldoantf,
			BigDecimal principalf, BigDecimal interesmf,
			BigDecimal cargoadminf, int nosol, String tiposol, String hechopor,
			Date fechaec, BigDecimal saldof, long iddec, String codsuc,
			String codunineg, int nodoc, String tipodoc, String partida,
			int nodocm, String tipodocm, Date fecha, Date fechavcto,
			BigDecimal monto, BigDecimal montop, String moneda,
			String concepto, int tipomov, int nodoco, String tipodoco,
			String nombre, String domicilio, String correoe, String unegocio,
			String tipomovimiento, String estadoec, int codestadoec,
			int idlogestcta, String drdl01, Date fechafact) {
		this.idec = idec;
		this.codcomp = codcomp;
		this.codclie = codclie;
		this.mes = mes;
		this.anio = anio;
		this.saldoantd = saldoantd;
		this.saldod = saldod;
		this.principald = principald;
		this.ineteresmd = ineteresmd;
		this.cargoadmind = cargoadmind;
		this.saldoantf = saldoantf;
		this.principalf = principalf;
		this.interesmf = interesmf;
		this.cargoadminf = cargoadminf;
		this.nosol = nosol;
		this.tiposol = tiposol;
		this.hechopor = hechopor;
		this.fechaec = fechaec;
		this.saldof = saldof;
		this.iddec = iddec;
		this.codsuc = codsuc;
		this.codunineg = codunineg;
		this.nodoc = nodoc;
		this.tipodoc = tipodoc;
		this.partida = partida;
		this.nodocm = nodocm;
		this.tipodocm = tipodocm;
		this.fecha = fecha;
		this.fechavcto = fechavcto;
		this.monto = monto;
		this.montop = montop;
		this.moneda = moneda;
		this.concepto = concepto;
		this.tipomov = tipomov;
		this.nodoco = nodoco;
		this.tipodoco = tipodoco;
		this.nombre = nombre;
		this.domicilio = domicilio;
		this.correoe = correoe;
		this.unegocio = unegocio;
		this.tipomovimiento = tipomovimiento;
		this.estadoec = estadoec;
		this.codestadoec = codestadoec;
		this.idlogestcta = idlogestcta;
		this.drdl01 = drdl01;
		this.fechafact = fechafact;
	}

	public long getIdec() {
		return this.idec;
	}

	public void setIdec(long idec) {
		this.idec = idec;
	}

	public String getCodcomp() {
		return this.codcomp;
	}

	public void setCodcomp(String codcomp) {
		this.codcomp = codcomp;
	}

	public int getCodclie() {
		return this.codclie;
	}

	public void setCodclie(int codclie) {
		this.codclie = codclie;
	}

	public int getMes() {
		return this.mes;
	}

	public void setMes(int mes) {
		this.mes = mes;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public BigDecimal getSaldoantd() {
		return this.saldoantd;
	}

	public void setSaldoantd(BigDecimal saldoantd) {
		this.saldoantd = saldoantd;
	}

	public BigDecimal getSaldod() {
		return this.saldod;
	}

	public void setSaldod(BigDecimal saldod) {
		this.saldod = saldod;
	}

	public BigDecimal getPrincipald() {
		return this.principald;
	}

	public void setPrincipald(BigDecimal principald) {
		this.principald = principald;
	}

	public BigDecimal getIneteresmd() {
		return this.ineteresmd;
	}

	public void setIneteresmd(BigDecimal ineteresmd) {
		this.ineteresmd = ineteresmd;
	}

	public BigDecimal getCargoadmind() {
		return this.cargoadmind;
	}

	public void setCargoadmind(BigDecimal cargoadmind) {
		this.cargoadmind = cargoadmind;
	}

	public BigDecimal getSaldoantf() {
		return this.saldoantf;
	}

	public void setSaldoantf(BigDecimal saldoantf) {
		this.saldoantf = saldoantf;
	}

	public BigDecimal getPrincipalf() {
		return this.principalf;
	}

	public void setPrincipalf(BigDecimal principalf) {
		this.principalf = principalf;
	}

	public BigDecimal getInteresmf() {
		return this.interesmf;
	}

	public void setInteresmf(BigDecimal interesmf) {
		this.interesmf = interesmf;
	}

	public BigDecimal getCargoadminf() {
		return this.cargoadminf;
	}

	public void setCargoadminf(BigDecimal cargoadminf) {
		this.cargoadminf = cargoadminf;
	}

	public int getNosol() {
		return this.nosol;
	}

	public void setNosol(int nosol) {
		this.nosol = nosol;
	}

	public String getTiposol() {
		return this.tiposol;
	}

	public void setTiposol(String tiposol) {
		this.tiposol = tiposol;
	}

	public String getHechopor() {
		return this.hechopor;
	}

	public void setHechopor(String hechopor) {
		this.hechopor = hechopor;
	}

	public Date getFechaec() {
		return this.fechaec;
	}

	public void setFechaec(Date fechaec) {
		this.fechaec = fechaec;
	}

	public BigDecimal getSaldof() {
		return this.saldof;
	}

	public void setSaldof(BigDecimal saldof) {
		this.saldof = saldof;
	}

	public long getIddec() {
		return this.iddec;
	}

	public void setIddec(long iddec) {
		this.iddec = iddec;
	}

	public String getCodsuc() {
		return this.codsuc;
	}

	public void setCodsuc(String codsuc) {
		this.codsuc = codsuc;
	}

	public String getCodunineg() {
		return this.codunineg;
	}

	public void setCodunineg(String codunineg) {
		this.codunineg = codunineg;
	}

	public int getNodoc() {
		return this.nodoc;
	}

	public void setNodoc(int nodoc) {
		this.nodoc = nodoc;
	}

	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public String getPartida() {
		return this.partida;
	}

	public void setPartida(String partida) {
		this.partida = partida;
	}

	public int getNodocm() {
		return this.nodocm;
	}

	public void setNodocm(int nodocm) {
		this.nodocm = nodocm;
	}

	public String getTipodocm() {
		return this.tipodocm;
	}

	public void setTipodocm(String tipodocm) {
		this.tipodocm = tipodocm;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechavcto() {
		return this.fechavcto;
	}

	public void setFechavcto(Date fechavcto) {
		this.fechavcto = fechavcto;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public BigDecimal getMontop() {
		return this.montop;
	}

	public void setMontop(BigDecimal montop) {
		this.montop = montop;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public int getTipomov() {
		return this.tipomov;
	}

	public void setTipomov(int tipomov) {
		this.tipomov = tipomov;
	}

	public int getNodoco() {
		return this.nodoco;
	}

	public void setNodoco(int nodoco) {
		this.nodoco = nodoco;
	}

	public String getTipodoco() {
		return this.tipodoco;
	}

	public void setTipodoco(String tipodoco) {
		this.tipodoco = tipodoco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getCorreoe() {
		return this.correoe;
	}

	public void setCorreoe(String correoe) {
		this.correoe = correoe;
	}

	public String getUnegocio() {
		return this.unegocio;
	}

	public void setUnegocio(String unegocio) {
		this.unegocio = unegocio;
	}

	public String getTipomovimiento() {
		return this.tipomovimiento;
	}

	public void setTipomovimiento(String tipomovimiento) {
		this.tipomovimiento = tipomovimiento;
	}

	public String getEstadoec() {
		return this.estadoec;
	}

	public void setEstadoec(String estadoec) {
		this.estadoec = estadoec;
	}

	public int getCodestadoec() {
		return this.codestadoec;
	}

	public void setCodestadoec(int codestadoec) {
		this.codestadoec = codestadoec;
	}

	public int getIdlogestcta() {
		return this.idlogestcta;
	}

	public void setIdlogestcta(int idlogestcta) {
		this.idlogestcta = idlogestcta;
	}

	public String getDrdl01() {
		return this.drdl01;
	}

	public void setDrdl01(String drdl01) {
		this.drdl01 = drdl01;
	}

	public Date getFechafact() {
		return this.fechafact;
	}

	public void setFechafact(Date fechafact) {
		this.fechafact = fechafact;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwdetestadoctaId))
			return false;
		VwdetestadoctaId castOther = (VwdetestadoctaId) other;

		return (this.getIdec() == castOther.getIdec())
				&& ((this.getCodcomp() == castOther.getCodcomp()) || (this
						.getCodcomp() != null && castOther.getCodcomp() != null && this
						.getCodcomp().equals(castOther.getCodcomp())))
				&& (this.getCodclie() == castOther.getCodclie())
				&& (this.getMes() == castOther.getMes())
				&& (this.getAnio() == castOther.getAnio())
				&& ((this.getSaldoantd() == castOther.getSaldoantd()) || (this
						.getSaldoantd() != null
						&& castOther.getSaldoantd() != null && this
						.getSaldoantd().equals(castOther.getSaldoantd())))
				&& ((this.getSaldod() == castOther.getSaldod()) || (this
						.getSaldod() != null && castOther.getSaldod() != null && this
						.getSaldod().equals(castOther.getSaldod())))
				&& ((this.getPrincipald() == castOther.getPrincipald()) || (this
						.getPrincipald() != null
						&& castOther.getPrincipald() != null && this
						.getPrincipald().equals(castOther.getPrincipald())))
				&& ((this.getIneteresmd() == castOther.getIneteresmd()) || (this
						.getIneteresmd() != null
						&& castOther.getIneteresmd() != null && this
						.getIneteresmd().equals(castOther.getIneteresmd())))
				&& ((this.getCargoadmind() == castOther.getCargoadmind()) || (this
						.getCargoadmind() != null
						&& castOther.getCargoadmind() != null && this
						.getCargoadmind().equals(castOther.getCargoadmind())))
				&& ((this.getSaldoantf() == castOther.getSaldoantf()) || (this
						.getSaldoantf() != null
						&& castOther.getSaldoantf() != null && this
						.getSaldoantf().equals(castOther.getSaldoantf())))
				&& ((this.getPrincipalf() == castOther.getPrincipalf()) || (this
						.getPrincipalf() != null
						&& castOther.getPrincipalf() != null && this
						.getPrincipalf().equals(castOther.getPrincipalf())))
				&& ((this.getInteresmf() == castOther.getInteresmf()) || (this
						.getInteresmf() != null
						&& castOther.getInteresmf() != null && this
						.getInteresmf().equals(castOther.getInteresmf())))
				&& ((this.getCargoadminf() == castOther.getCargoadminf()) || (this
						.getCargoadminf() != null
						&& castOther.getCargoadminf() != null && this
						.getCargoadminf().equals(castOther.getCargoadminf())))
				&& (this.getNosol() == castOther.getNosol())
				&& ((this.getTiposol() == castOther.getTiposol()) || (this
						.getTiposol() != null && castOther.getTiposol() != null && this
						.getTiposol().equals(castOther.getTiposol())))
				&& ((this.getHechopor() == castOther.getHechopor()) || (this
						.getHechopor() != null
						&& castOther.getHechopor() != null && this
						.getHechopor().equals(castOther.getHechopor())))
				&& ((this.getFechaec() == castOther.getFechaec()) || (this
						.getFechaec() != null && castOther.getFechaec() != null && this
						.getFechaec().equals(castOther.getFechaec())))
				&& ((this.getSaldof() == castOther.getSaldof()) || (this
						.getSaldof() != null && castOther.getSaldof() != null && this
						.getSaldof().equals(castOther.getSaldof())))
				&& (this.getIddec() == castOther.getIddec())
				&& ((this.getCodsuc() == castOther.getCodsuc()) || (this
						.getCodsuc() != null && castOther.getCodsuc() != null && this
						.getCodsuc().equals(castOther.getCodsuc())))
				&& ((this.getCodunineg() == castOther.getCodunineg()) || (this
						.getCodunineg() != null
						&& castOther.getCodunineg() != null && this
						.getCodunineg().equals(castOther.getCodunineg())))
				&& (this.getNodoc() == castOther.getNodoc())
				&& ((this.getTipodoc() == castOther.getTipodoc()) || (this
						.getTipodoc() != null && castOther.getTipodoc() != null && this
						.getTipodoc().equals(castOther.getTipodoc())))
				&& ((this.getPartida() == castOther.getPartida()) || (this
						.getPartida() != null && castOther.getPartida() != null && this
						.getPartida().equals(castOther.getPartida())))
				&& (this.getNodocm() == castOther.getNodocm())
				&& ((this.getTipodocm() == castOther.getTipodocm()) || (this
						.getTipodocm() != null
						&& castOther.getTipodocm() != null && this
						.getTipodocm().equals(castOther.getTipodocm())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getFechavcto() == castOther.getFechavcto()) || (this
						.getFechavcto() != null
						&& castOther.getFechavcto() != null && this
						.getFechavcto().equals(castOther.getFechavcto())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null && castOther.getMonto() != null && this
						.getMonto().equals(castOther.getMonto())))
				&& ((this.getMontop() == castOther.getMontop()) || (this
						.getMontop() != null && castOther.getMontop() != null && this
						.getMontop().equals(castOther.getMontop())))
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null && castOther.getMoneda() != null && this
						.getMoneda().equals(castOther.getMoneda())))
				&& ((this.getConcepto() == castOther.getConcepto()) || (this
						.getConcepto() != null
						&& castOther.getConcepto() != null && this
						.getConcepto().equals(castOther.getConcepto())))
				&& (this.getTipomov() == castOther.getTipomov())
				&& (this.getNodoco() == castOther.getNodoco())
				&& ((this.getTipodoco() == castOther.getTipodoco()) || (this
						.getTipodoco() != null
						&& castOther.getTipodoco() != null && this
						.getTipodoco().equals(castOther.getTipodoco())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getDomicilio() == castOther.getDomicilio()) || (this
						.getDomicilio() != null
						&& castOther.getDomicilio() != null && this
						.getDomicilio().equals(castOther.getDomicilio())))
				&& ((this.getCorreoe() == castOther.getCorreoe()) || (this
						.getCorreoe() != null && castOther.getCorreoe() != null && this
						.getCorreoe().equals(castOther.getCorreoe())))
				&& ((this.getUnegocio() == castOther.getUnegocio()) || (this
						.getUnegocio() != null
						&& castOther.getUnegocio() != null && this
						.getUnegocio().equals(castOther.getUnegocio())))
				&& ((this.getTipomovimiento() == castOther.getTipomovimiento()) || (this
						.getTipomovimiento() != null
						&& castOther.getTipomovimiento() != null && this
						.getTipomovimiento().equals(
								castOther.getTipomovimiento())))
				&& ((this.getEstadoec() == castOther.getEstadoec()) || (this
						.getEstadoec() != null
						&& castOther.getEstadoec() != null && this
						.getEstadoec().equals(castOther.getEstadoec())))
				&& (this.getCodestadoec() == castOther.getCodestadoec())
				&& (this.getIdlogestcta() == castOther.getIdlogestcta())
				&& ((this.getDrdl01() == castOther.getDrdl01()) || (this
						.getDrdl01() != null && castOther.getDrdl01() != null && this
						.getDrdl01().equals(castOther.getDrdl01())))
				&& ((this.getFechafact() == castOther.getFechafact()) || (this
						.getFechafact() != null
						&& castOther.getFechafact() != null && this
						.getFechafact().equals(castOther.getFechafact())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdec();
		result = 37 * result
				+ (getCodcomp() == null ? 0 : this.getCodcomp().hashCode());
		result = 37 * result + this.getCodclie();
		result = 37 * result + this.getMes();
		result = 37 * result + this.getAnio();
		result = 37 * result
				+ (getSaldoantd() == null ? 0 : this.getSaldoantd().hashCode());
		result = 37 * result
				+ (getSaldod() == null ? 0 : this.getSaldod().hashCode());
		result = 37
				* result
				+ (getPrincipald() == null ? 0 : this.getPrincipald()
						.hashCode());
		result = 37
				* result
				+ (getIneteresmd() == null ? 0 : this.getIneteresmd()
						.hashCode());
		result = 37
				* result
				+ (getCargoadmind() == null ? 0 : this.getCargoadmind()
						.hashCode());
		result = 37 * result
				+ (getSaldoantf() == null ? 0 : this.getSaldoantf().hashCode());
		result = 37
				* result
				+ (getPrincipalf() == null ? 0 : this.getPrincipalf()
						.hashCode());
		result = 37 * result
				+ (getInteresmf() == null ? 0 : this.getInteresmf().hashCode());
		result = 37
				* result
				+ (getCargoadminf() == null ? 0 : this.getCargoadminf()
						.hashCode());
		result = 37 * result + this.getNosol();
		result = 37 * result
				+ (getTiposol() == null ? 0 : this.getTiposol().hashCode());
		result = 37 * result
				+ (getHechopor() == null ? 0 : this.getHechopor().hashCode());
		result = 37 * result
				+ (getFechaec() == null ? 0 : this.getFechaec().hashCode());
		result = 37 * result
				+ (getSaldof() == null ? 0 : this.getSaldof().hashCode());
		result = 37 * result + (int) this.getIddec();
		result = 37 * result
				+ (getCodsuc() == null ? 0 : this.getCodsuc().hashCode());
		result = 37 * result
				+ (getCodunineg() == null ? 0 : this.getCodunineg().hashCode());
		result = 37 * result + this.getNodoc();
		result = 37 * result
				+ (getTipodoc() == null ? 0 : this.getTipodoc().hashCode());
		result = 37 * result
				+ (getPartida() == null ? 0 : this.getPartida().hashCode());
		result = 37 * result + this.getNodocm();
		result = 37 * result
				+ (getTipodocm() == null ? 0 : this.getTipodocm().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getFechavcto() == null ? 0 : this.getFechavcto().hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37 * result
				+ (getMontop() == null ? 0 : this.getMontop().hashCode());
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result
				+ (getConcepto() == null ? 0 : this.getConcepto().hashCode());
		result = 37 * result + this.getTipomov();
		result = 37 * result + this.getNodoco();
		result = 37 * result
				+ (getTipodoco() == null ? 0 : this.getTipodoco().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getDomicilio() == null ? 0 : this.getDomicilio().hashCode());
		result = 37 * result
				+ (getCorreoe() == null ? 0 : this.getCorreoe().hashCode());
		result = 37 * result
				+ (getUnegocio() == null ? 0 : this.getUnegocio().hashCode());
		result = 37
				* result
				+ (getTipomovimiento() == null ? 0 : this.getTipomovimiento()
						.hashCode());
		result = 37 * result
				+ (getEstadoec() == null ? 0 : this.getEstadoec().hashCode());
		result = 37 * result + this.getCodestadoec();
		result = 37 * result + this.getIdlogestcta();
		result = 37 * result
				+ (getDrdl01() == null ? 0 : this.getDrdl01().hashCode());
		result = 37 * result
				+ (getFechafact() == null ? 0 : this.getFechafact().hashCode());
		return result;
	}

}
