package ni.com.casapellas.cxccobro.cxc;

// Generated Jan 14, 2012 1:23:29 PM by Hibernate Tools 3.2.2.GA

/**
 * Vwdetestadocta generated by hbm2java
 */
public class Vwdetestadocta implements java.io.Serializable {

	private VwdetestadoctaId id;

	public Vwdetestadocta() {
	}

	public Vwdetestadocta(VwdetestadoctaId id) {
		this.id = id;
	}

	public VwdetestadoctaId getId() {
		return this.id;
	}

	public void setId(VwdetestadoctaId id) {
		this.id = id;
	}

}
