package ni.com.casapellas.cxccobro.cxc;

// Generated Jan 24, 2012 3:09:02 PM by Hibernate Tools 3.2.2.GA

/**
 * Vwhdrestcta generated by hbm2java
 */
public class Vwhdrestcta implements java.io.Serializable {

	private VwhdrestctaId id;
	private String observacion;
	private int cantidad;
	private String estado;

	public Vwhdrestcta() {
	}

	public Vwhdrestcta(VwhdrestctaId id) {
		this.id = id;
	}

	public VwhdrestctaId getId() {
		return this.id;
	}

	public void setId(VwhdrestctaId id) {
		this.id = id;
	}

	public String getObservacion() {
		return observacion;
	}

	public int getCantidad() {
		return cantidad;
	}

	public String getEstado() {
		return estado;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
